import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';

// public/downtown.json is generated by the release process from one source of truth. The page
// renders only from it, so this is the contract the page and outside readers rely on.
const data = JSON.parse(readFileSync(new URL('../public/downtown.json', import.meta.url), 'utf8'));
const ORG = 'https://github.com/centralcity-ai';
const DATE = /^\d{4}-\d{2}-\d{2}$/;
const VERSION = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const ID = /^[a-z0-9][a-z0-9-]{0,62}$/;

test('downtown.json has the v2 shape', () => {
  assert.equal(data.schema, 'centralcity.downtown/v2');
  assert.match(data.updated, DATE);
  for (const key of ['public_repositories', 'categories', 'districts', 'roadmap'])
    assert.ok(Array.isArray(data[key]) && data[key].length > 0, key);
  for (const key of ['start', 'contribute', 'ai_builders', 'sync'])
    assert.equal(typeof data[key], 'object', key);
});

test('every public repository is a centralcity-ai repository with a coherent release', () => {
  const names = new Set<string>();
  for (const repo of data.public_repositories) {
    assert.match(repo.name, /^centralcity-ai\/[a-z0-9-]+$/);
    assert.ok(!names.has(repo.name), `duplicate ${repo.name}`);
    names.add(repo.name);
    assert.equal(repo.url, `https://github.com/${repo.name}`);
    assert.equal(repo.changelog, `${repo.url}/blob/main/CHANGELOG.md`);
    assert.equal(repo.license, 'Apache-2.0');
    if (repo.version !== null) {
      assert.match(repo.version, VERSION, repo.name);
      assert.match(repo.last_synced, DATE, repo.name);
    } else assert.equal(repo.last_synced, null, repo.name);
  }
});

test('districts are unique, categorised, and released ones link to a released public repository', () => {
  const repos = new Map<string, any>(data.public_repositories.map((repo: any) => [repo.url, repo]));
  const categories = new Set<string>(data.categories.map((category: any) => category.id));
  assert.equal(categories.size, data.categories.length, 'duplicate category id');
  const ids = new Set<string>();
  for (const district of data.districts) {
    assert.match(district.id, ID);
    assert.ok(!ids.has(district.id), `duplicate district ${district.id}`);
    ids.add(district.id);
    assert.ok(categories.has(district.category), `${district.id}: unknown category`);
    assert.ok(['released', 'review', 'planned'].includes(district.status), district.id);
    assert.ok(district.name && district.purpose, district.id);
    assert.equal(district.license, 'Apache-2.0');
    if (district.repository !== null)
      assert.ok(repos.has(district.repository), `${district.id}: repository is not public`);
    if (district.status === 'released') {
      const repo = repos.get(district.repository);
      assert.ok(repo && repo.version, `${district.id}: released without a released repository`);
      assert.ok(
        district.source === repo.url || district.source.startsWith(`${repo.url}/tree/main/`),
        `${district.id}: source outside its repository`,
      );
      assert.equal(district.version, repo.version);
      assert.equal(district.last_synced, repo.last_synced);
      assert.equal(district.changelog, repo.changelog);
    } else {
      for (const key of ['source', 'version', 'last_synced', 'changelog'])
        assert.equal(district[key], null, `${district.id}: ${key} before release`);
    }
  }
  for (const category of data.categories)
    assert.equal(
      category.count,
      data.districts.filter((district: any) => district.category === category.id).length,
      category.id,
    );
});

test('downtown.json and downtown.md link only to public Central City repositories', () => {
  const markdown = readFileSync(new URL('../public/downtown.md', import.meta.url), 'utf8');
  const allowed = new Set<string>(data.public_repositories.map((repo: any) => repo.url));
  for (const text of [JSON.stringify(data), markdown])
    for (const url of text.match(/https:\/\/github\.com\/[^\s")|]*/g) ?? []) {
      assert.ok(url === ORG || url.startsWith(`${ORG}/`), url);
      const repo = url.split('/').slice(0, 5).join('/');
      assert.ok(url === ORG || allowed.has(repo), `${url} is not a listed public repository`);
    }
});

test('Downtown is Live: no preview, pre-release or beta wording outside package versions', () => {
  assert.equal(data.status, 'Live');
  const markdown = readFileSync(new URL('../public/downtown.md', import.meta.url), 'utf8');
  // Versions keep their honest semver (e.g. 0.1.0-alpha.5), so they are removed before the check.
  const prose = (text: string) => text.replace(/\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?/g, '');
  const wording = /\b(pre-?release|preview|beta)\b/i;
  const strings: string[] = [];
  JSON.stringify(data, (key, value) => {
    if (typeof value === 'string' && key !== 'version') strings.push(value);
    return value;
  });
  for (const text of [...strings, markdown]) assert.doesNotMatch(prose(text), wording);
});
