import { test, expect, type Page } from '@playwright/test';
import { readFileSync } from 'node:fs';

/*
 * The page renders from public/downtown.json, generated by the release process from one source of
 * truth. These tests read the same file, so adding a project needs no test change; the rules
 * (what may link where) are checked against the data.
 */
type District = {
  id: string;
  name: string;
  purpose: string;
  category: string;
  status: 'released' | 'review' | 'planned';
  repository: string | null;
  source: string | null;
  version: string | null;
  last_synced: string | null;
  changelog: string | null;
  note?: string;
};
const data = JSON.parse(readFileSync(new URL('../public/downtown.json', import.meta.url), 'utf8'));
const districts: District[] = data.districts;
const org = 'https://github.com/centralcity-ai';
const toolkit = `${org}/toolkit`;
const repositories: string[] = data.public_repositories.map((repo: { url: string }) => repo.url);
/** The only GitHub links the page may carry: public repositories, released sources, changelogs, guide. */
const allowedLinks = [
  ...new Set([
    org,
    ...repositories,
    ...data.public_repositories.map((repo: { changelog: string }) => repo.changelog),
    ...districts.flatMap((d) => [d.source, d.changelog]).filter((url): url is string => !!url),
    data.contribute.guide as string,
  ]),
];
const statusLabel = { released: 'Released', review: 'In review', planned: 'Planned' };

/*
 * /downtown is a client route. Vercel rewrites it to index.html; the local test server
 * (server/index.ts) only does that for its CLIENT_ROUTES allowlist, which does not list
 * /downtown yet. Until it does, each test answers the hard navigation with the same index.html
 * the server returns for "/", which is exactly what the production rewrite serves. App.tsx then
 * chooses the page from window.location.pathname, so no test hook is needed in the app.
 */
async function openDowntown(page: Page, path = '/downtown') {
  await page.route(/\/downtown\/?$/, async (route) => {
    const response = await route.fetch({ url: new URL('/', route.request().url()).toString() });
    await route.fulfill({ response });
  });
  await page.goto(path);
  await expect(page.getByRole('heading', { level: 1, name: 'Downtown' })).toBeVisible();
  await expect(page.locator('#explore .dt-row').first()).toBeVisible();
}

test('downtown shows the exact copy and only actions with working destinations', async ({
  page,
}) => {
  const errors: string[] = [];
  page.on('pageerror', (error) => errors.push(error.message));
  await openDowntown(page);
  await expect(page).toHaveTitle('Downtown · Central City');
  const hero = page.getByRole('region', { name: 'Downtown' });
  await expect(
    hero.getByText(
      'Downtown is the public part of Central City: code, protocol schemas, test suites and documentation, organized into numbered districts.',
      { exact: true },
    ),
  ).toBeVisible();

  // Design v8 hero actions: the GitHub organization, the Verify page and the start steps.
  const actions = hero.locator('.button');
  await expect(actions).toHaveCount(3);
  await expect(actions.nth(0)).toHaveText('GitHub organization');
  await expect(actions.nth(0)).toHaveAttribute('href', org);
  await expect(actions.nth(1)).toHaveText(/^Verify the agent count( \([\d,]+\))?$/);
  await expect(actions.nth(1)).toHaveAttribute('href', '/downtown/verify');
  await expect(actions.nth(2)).toHaveText('Start building');
  await expect(actions.nth(2)).toHaveAttribute('href', '#start');
  // The live count, never a sample number.
  await expect(actions.nth(1)).not.toContainText('2,847');
  await expect(page.getByRole('button', { name: /contribute/i })).toHaveCount(0);
  const contribute = page.locator('#contribute');
  await expect(contribute).toContainText('Contribute to the toolkit.');
  await expect(contribute).not.toContainText('nothing to fork');
  await expect(contribute.getByRole('link')).toHaveCount(1);
  await expect(contribute.getByRole('link', { name: 'Read CONTRIBUTING.md' })).toHaveAttribute(
    'href',
    `${toolkit}/blob/main/CONTRIBUTING.md`,
  );
  // The shared public footer (src/shell), not a page-specific one.
  await expect(page.locator('footer')).toContainText(
    'Open protocol, toolkit and SDK under Apache-2.0',
  );

  // GitHub links: only public repositories, released sources, changelogs and the guide.
  const hrefs = await page
    .locator('a[href]')
    .evaluateAll((links) => links.map((link) => link.getAttribute('href')!));
  const github = [...new Set(hrefs.filter((href) => /github\.com/i.test(href)))];
  expect(github.filter((href) => !allowedLinks.includes(href))).toEqual([]);
  await expect(hero).toContainText(/Last synced \d{4}-\d{2}-\d{2}/);
  await expect(
    hero.getByRole('link', { name: `All ${repositories.length} repositories` }),
  ).toHaveAttribute('href', org);
  // No city visuals: no map, no markers, no looping animation.
  await expect(page.locator('.dt-map, .dt-marker, svg.dt-skyline')).toHaveCount(0);
  expect(
    await page.evaluate(
      () =>
        document.getAnimations().filter((a) => a.effect?.getTiming().iterations === Infinity)
          .length,
    ),
  ).toBe(0);

  // Seven districts (design v8), each from the live data.
  const cards = page.locator('#districts .dt-district');
  await expect(cards).toHaveCount(7);
  for (let index = 0; index < 7; index++)
    await expect(cards.nth(index).locator('.dt-district-num')).toContainText(
      `District ${index + 1}`,
    );
  for (const repo of data.public_repositories as {
    name: string;
    title: string;
    url: string;
    version: string | null;
  }[]) {
    const card = cards.filter({ has: page.getByRole('link', { name: `${repo.title} on GitHub` }) });
    await expect(card).toHaveCount(1);
    await expect(card.getByRole('link', { name: `${repo.title} on GitHub` })).toHaveAttribute(
      'href',
      repo.url,
    );
    // The badge follows the district's main repository (the first one listed).
    if ((await card.getByRole('link', { name: /on GitHub$/ }).count()) === 1)
      await expect(card.locator('.dt-pill')).toContainText(
        repo.version ? `v${repo.version}` : 'Being set up',
      );
  }
  await expect(
    page.locator('#district-5').getByRole('link', { name: 'Verify the count' }),
  ).toHaveAttribute('href', '/downtown/verify');
  await expect(
    page.locator('#district-6').getByRole('link', { name: 'Security overview' }),
  ).toHaveAttribute('href', '/security');
  const reference = districts.find((d) => d.id === 'reference')!;
  await expect(page.locator('#district-7 .dt-pill')).toHaveText(statusLabel[reference.status]);

  // Each category is a quiet link with its count, above the project list.
  const counts = page.locator('#explore .dt-counts');
  for (const category of data.categories)
    await expect(counts.getByRole('link', { name: category.name, exact: true })).toHaveAttribute(
      'href',
      `#category-${category.id}`,
    );
  // Every in-page anchor has a target.
  for (const href of hrefs.filter((value) => value.startsWith('#')))
    await expect(page.locator(`[id="${href.slice(1)}"]`), href).toHaveCount(1);
  for (const id of ['districts', 'explore', 'start', 'contribute', 'ai', 'next'])
    await expect(page.locator(`section#${id}`)).toHaveCount(1);

  // One row per project, grouped under its category.
  await expect(page.locator('#explore .dt-row')).toHaveCount(districts.length);
  for (const district of districts) {
    const row = page.locator(`#category-${district.category} #district-${district.id}`);
    await expect(row.locator('.dt-badge')).toHaveText(statusLabel[district.status]);
    const meta = row.locator('.dt-meta');
    if (district.status === 'released') {
      await expect(meta).not.toContainText('(planned)');
      await expect(row.getByRole('link', { name: /on GitHub$/ })).toHaveAttribute(
        'href',
        district.source!,
      );
      await expect(meta).toContainText(`Version ${district.version}`);
      await expect(meta).toContainText(/Synced \d{4}-\d{2}-\d{2}/);
      await expect(row.getByRole('link', { name: /changelog$/ })).toHaveAttribute(
        'href',
        district.changelog!,
      );
    } else {
      await expect(meta).toContainText('Apache-2.0 (planned)');
      await expect(row.getByRole('link', { name: /on GitHub$|changelog$/ })).toHaveCount(0);
      if (district.repository)
        await expect(row.getByRole('link', { name: /not released yet/ })).toHaveAttribute(
          'href',
          district.repository,
        );
      else await expect(row).toContainText('Published with the release');
    }
    if (district.note) await expect(row).toContainText(district.note);
  }
  // Roadmap: Phase 1 (the protocol repository) is done.
  const phases = page.locator('#next .dt-roadmap li');
  await expect(phases.nth(0).locator('.dt-badge')).toHaveText('Done');
  await expect(phases.nth(1).locator('.dt-badge')).toHaveText('In progress');
  await expect(phases.nth(2).locator('.dt-badge')).toHaveText('Planned');

  // Start building scrolls to its section.
  await actions.nth(2).click();
  await expect(page).toHaveURL(/\/downtown#start$/);
  await expect(page.locator('#start')).toBeInViewport();
  expect(errors).toEqual([]);
});

test('downtown machine-readable files are served and honest', async ({ page, request }) => {
  const json = await request.get('/downtown.json');
  expect(json.ok()).toBe(true);
  const served = await json.json();
  expect(served).toEqual(data);
  expect(served.schema).toBe('centralcity.downtown/v2');
  expect(served.status).toBe('Live');
  expect(JSON.stringify(served)).not.toContain('city.desk');
  expect(served.contribute.guide).toBe(`${toolkit}/blob/main/CONTRIBUTING.md`);
  expect(served.start.mcp_url).toBe('https://centralcity.ai/mcp/open');
  const jsonLinks: string[] = JSON.stringify(served).match(/https:\/\/github\.com[^"]*/g) ?? [];
  expect(jsonLinks.filter((url) => !allowedLinks.includes(url))).toEqual([]);

  const markdown = await request.get('/downtown.md');
  expect(markdown.ok()).toBe(true);
  const text = await markdown.text();
  for (const repo of served.public_repositories)
    expect(text).toContain(`[${repo.name}](${repo.url})`);
  for (const district of districts) expect(text).toContain(`| ${district.name} |`);
  for (const url of text.match(/https:\/\/github\.com[^\s)|]*/g) ?? [])
    expect(allowedLinks).toContain(url);

  await openDowntown(page);
  await expect(page.locator('#ai a[href="/downtown.json"]')).toBeVisible();
  await expect(page.locator('#ai a[href="/downtown.md"]')).toBeVisible();
});

test('downtown fits 360 px and the category links are keyboard operable', async ({ page }) => {
  await page.setViewportSize({ width: 360, height: 780 });
  await openDowntown(page);
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(0);
  const first = data.categories[0];
  const link = page.locator('.dt-counts').getByRole('link', { name: first.name, exact: true });
  let reached = false;
  for (let index = 0; index < 60 && !reached; index++) {
    await page.keyboard.press('Tab');
    reached = await link.evaluate((element) => element === document.activeElement);
  }
  expect(reached).toBe(true);
  const box = await link.boundingBox();
  expect(box!.height).toBeGreaterThanOrEqual(44);
  await page.keyboard.press('Enter');
  await expect(page).toHaveURL(new RegExp(`#category-${first.id}$`));
  await expect(page.locator(`#category-${first.id}`)).toBeInViewport();
});

test('downtown search and status filter narrow the projects', async ({ page }) => {
  await openDowntown(page);
  const cards = page.locator('#explore .dt-row');
  const results = page.locator('#explore .dt-results');
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('bridge');
  await expect(cards).toHaveCount(
    districts.filter((d) => /bridge/i.test(d.name + d.purpose)).length,
  );
  await expect(results).toContainText(`of ${districts.length} projects`);
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('zzz-nothing');
  await expect(cards).toHaveCount(0);
  await expect(page.locator('#explore .dt-empty')).toBeVisible();
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('');
  await page.getByRole('radio', { name: /^Released/ }).check();
  await expect(page.locator('.dt-filter label.is-selected > span')).toHaveAccessibleName(
    /^Released, \d+ projects?$/,
  );
  await expect(cards).toHaveCount(districts.filter((d) => d.status === 'released').length);
  await page.getByRole('radio', { name: /^All/ }).check();
  await expect(cards).toHaveCount(districts.length);
});

test('downtown scales to 500 projects', async ({ page }) => {
  // Synthetic data in the published shape: 12 categories, 500 districts.
  const categories = Array.from({ length: 12 }, (_, index) => ({
    id: `cat-${index}`,
    name: `Category ${index}`,
    summary: 'Synthetic category.',
    count: 0,
  }));
  const many = Array.from({ length: 500 }, (_, index) => ({
    id: `d-${index}`,
    name: `District ${index}`,
    category: `cat-${index % 12}`,
    status: (['released', 'review', 'planned'] as const)[index % 3],
    purpose: 'Synthetic district.',
    license: 'Apache-2.0',
    repository: `${org}/protocol`,
    source: index % 3 === 0 ? `${org}/protocol` : null,
    version: index % 3 === 0 ? '1.0.0' : null,
    last_synced: index % 3 === 0 ? '2026-09-28' : null,
    changelog: index % 3 === 0 ? `${org}/protocol/blob/main/CHANGELOG.md` : null,
  }));
  for (const category of categories)
    category.count = many.filter((d) => d.category === category.id).length;
  await page.route('**/downtown.json', (route) =>
    route.fulfill({ json: { ...data, categories, districts: many } }),
  );
  await page.setViewportSize({ width: 360, height: 800 });
  await openDowntown(page);
  // The category links list the categories with their counts, never one entry per project.
  await expect(page.locator('.dt-counts').getByRole('link')).toHaveCount(12);
  // Each category previews 12 projects until expanded.
  await expect(page.locator('#explore .dt-row')).toHaveCount(12 * 12);
  await page.getByRole('button', { name: /Show all \d+ in Category 0$/ }).click();
  await expect(page.locator('#category-cat-0 .dt-row')).toHaveCount(42);
  // Filtering shows every match.
  await page.getByRole('searchbox', { name: 'Search projects' }).fill('District 49');
  await expect(page.locator('#explore .dt-row')).toHaveCount(11);
  const overflow = await page.evaluate(
    () => document.documentElement.scrollWidth - document.documentElement.clientWidth,
  );
  expect(overflow).toBeLessThanOrEqual(0);
  // A direct link to a project inside a collapsed category opens it.
  await page.goto('about:blank');
  await page.goto('/downtown#district-d-491');
  await expect(page.locator('#district-d-491')).toBeFocused();
});

test('downtown runs no animations with reduced motion', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await openDowntown(page);
  await page.locator('.dt-row').first().hover();
  const state = await page.evaluate(() => ({
    running: document.getAnimations().filter((animation) => animation.playState === 'running')
      .length,
    total: document.getAnimations().length,
    scroll: getComputedStyle(document.documentElement).scrollBehavior,
  }));
  expect(state).toEqual({ running: 0, total: 0, scroll: 'auto' });

  // Without the preference there is still no looping animation.
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.reload();
  await expect(page.locator('#explore .dt-row').first()).toBeVisible();
  expect(
    await page.evaluate(
      () =>
        document.getAnimations().filter((a) => a.effect?.getTiming().iterations === Infinity)
          .length,
    ),
  ).toBe(0);
});

/** Waits for running CSS transitions, so colours are measured at rest rather than mid-fade. */
async function settleTransitions(page: Page) {
  await page.evaluate(() =>
    Promise.all(
      document
        .getAnimations()
        .filter((animation) => animation instanceof CSSTransition)
        .map((animation) => animation.finished.catch(() => undefined)),
    ),
  );
}

/** Every visible text node in the page, with its colour and the nearest opaque background. */
async function textContrast(page: Page) {
  await settleTransitions(page);
  return page.evaluate(() => {
    const canvas = document.createElement('canvas').getContext('2d')!;
    // Normalise any CSS colour (including color-mix results) to sRGB bytes via a 1 px canvas.
    const rgba = (color: string) => {
      canvas.clearRect(0, 0, 1, 1);
      canvas.fillStyle = color;
      canvas.fillRect(0, 0, 1, 1);
      return [...canvas.getImageData(0, 0, 1, 1).data];
    };
    const luminance = ([r, g, b]: number[]) =>
      [r, g, b]
        .map((value) => value / 255)
        .map((value) => (value <= 0.03928 ? value / 12.92 : ((value + 0.055) / 1.055) ** 2.4))
        .reduce((sum, value, index) => sum + value * [0.2126, 0.7152, 0.0722][index], 0);
    const background = (element: Element | null): number[] => {
      for (; element; element = element.parentElement) {
        const value = rgba(getComputedStyle(element).backgroundColor);
        if (value[3] > 200) return value;
      }
      return rgba(getComputedStyle(document.body).backgroundColor);
    };
    // Where a failing pair sits, so a report names the element, not just its text.
    const where = (element: Element) => {
      const parts: string[] = [];
      for (
        let node: Element | null = element;
        node && node !== document.body;
        node = node.parentElement
      ) {
        parts.unshift(
          node.tagName.toLowerCase() + [...node.classList].map((name) => `.${name}`).join(''),
        );
        if (parts.length === 3) break;
      }
      return parts.join(' > ');
    };
    const results: {
      text: string;
      where: string;
      colors: string;
      ratio: number;
      minimum: number;
    }[] = [];
    const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT);
    while (walker.nextNode()) {
      const node = walker.currentNode;
      const element = node.parentElement!;
      const style = getComputedStyle(element);
      if (!node.textContent!.trim() || !element.checkVisibility({ opacityProperty: true }))
        continue;
      const [foreground, back] = [rgba(style.color), background(element)];
      const [a, b] = [luminance(foreground), luminance(back)];
      const large =
        parseFloat(style.fontSize) >= 24 ||
        (parseFloat(style.fontSize) >= 18.66 && Number(style.fontWeight) >= 700);
      results.push({
        text: node.textContent!.trim().slice(0, 40),
        where: where(element),
        colors: `rgb(${foreground.slice(0, 3)}) on rgb(${back.slice(0, 3)})`,
        ratio: Math.round(((Math.max(a, b) + 0.05) / (Math.min(a, b) + 0.05)) * 100) / 100,
        // WCAG AA is 4.5 (3 for large text); require a 0.1 margin so rendering differences
        // between browsers and platforms cannot tip a pair under the line.
        minimum: large ? 3.1 : 4.6,
      });
    }
    return results;
  });
}

test('downtown has named landmarks, ordered headings and labelled controls', async ({ page }) => {
  await openDowntown(page);
  for (const role of ['banner', 'main', 'contentinfo'] as const)
    await expect(page.getByRole(role)).toHaveCount(1);
  await expect(page.getByRole('navigation', { name: 'Public' })).toHaveCount(1);
  for (const name of ['Projects', 'Build today, without our repositories.'])
    await expect(page.getByRole('region', { name })).toHaveCount(1);
  const levels = await page
    .locator('main :is(h1, h2, h3, h4, h5, h6)')
    .evaluateAll((headings) => headings.map((heading) => Number(heading.tagName[1])));
  expect(levels[0]).toBe(1);
  for (let index = 1; index < levels.length; index++)
    expect(levels[index] - levels[index - 1], `heading ${index}`).toBeLessThanOrEqual(1);

  // The status filter is a labelled group whose options say what they count.
  await expect(page.getByRole('group', { name: 'Status' })).toHaveCount(1);

  // Each Copy button sits in a group that says what it copies.
  for (const name of ['Claude Code', 'Codex'])
    await expect(
      page.getByRole('group', { name }).getByRole('button', { name: 'Copy' }),
    ).toHaveCount(1);
  // Every link and button has an accessible name.
  for (const control of await page.locator('main a, main button, header a, header button').all())
    expect(
      await control.evaluate(
        (element) => element.textContent!.trim() || element.getAttribute('aria-label'),
      ),
    ).toBeTruthy();

  // Keyboard focus is visible on the category links.
  const link = page.locator('.dt-counts a').first();
  await link.focus();
  await page.keyboard.press('Shift+Tab');
  await page.keyboard.press('Tab');
  const outline = await link.evaluate((element) => getComputedStyle(element).outlineStyle);
  expect(outline).not.toBe('none');

  const contrast = await textContrast(page);
  expect(contrast.length).toBeGreaterThan(60);
  const low = contrast.filter((item) => item.ratio < item.minimum);
  expect(low, 'text pairs under the contrast minimum (where, colours, ratio)').toEqual([]);
});

for (const width of [390, 1440]) {
  test(`downtown renders in the dark theme at ${width} px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 });
    await page.addInitScript((theme) => localStorage.setItem('cc-theme', theme), 'dark');
    await openDowntown(page);
    const colours = await page.evaluate(() => ({
      canvas: getComputedStyle(document.body).backgroundColor,
      segments: getComputedStyle(document.querySelector('.dt-segments')!).backgroundColor,
      code: getComputedStyle(document.querySelector('.dt-code-row')!).backgroundColor,
      heading: getComputedStyle(document.querySelector('h1')!).color,
    }));
    // Brand dark tokens: ink canvas, night cards, sunken code rows, white text.
    expect(colours).toEqual({
      canvas: 'rgb(9, 9, 11)',
      segments: 'rgb(18, 18, 20)',
      code: 'rgb(18, 18, 20)',
      heading: 'rgb(250, 250, 250)',
    });
    for (const text of [
      'District 1 · Core specifications',
      'Projects',
      'Contribute to the toolkit.',
    ])
      await expect(page.getByText(text, { exact: true })).toBeVisible();
    const contrast = await textContrast(page);
    expect(contrast.length).toBeGreaterThan(60);
    const low = contrast.filter((item) => item.ratio < item.minimum);
    expect(low, 'text pairs under the contrast minimum (where, colours, ratio)').toEqual([]);

    // The in-page toggle agrees: picking light from dark flips the tokens.
    // Under 900 px the theme toggle lives in the header menu.
    if (width < 900) await page.getByRole('button', { name: 'Open menu' }).click();
    await page.getByRole('button', { name: 'Use light theme' }).click();
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
    await expect
      .poll(() => page.evaluate(() => getComputedStyle(document.body).backgroundColor))
      .toBe('rgb(255, 255, 255)');
  });
}

test('downtown GitHub links resolve for a signed-out visitor', async ({ playwright }) => {
  // A fresh context with no cookies or tokens: every released link must be public (HTTP 200).
  // Opt out with DOWNTOWN_SKIP_NETWORK=1 on machines without internet access.
  test.skip(process.env.DOWNTOWN_SKIP_NETWORK === '1', 'network checks disabled');
  const anonymous = await playwright.request.newContext();
  try {
    for (const url of allowedLinks) {
      const response = await anonymous.get(url, { maxRedirects: 5 });
      expect(response.status(), url).toBe(200);
    }
  } finally {
    await anonymous.dispose();
  }
});

test('"Last synced" sits close to the first district (no double gap)', async ({ page }) => {
  await page.setViewportSize({ width: 1440, height: 900 });
  await page.goto('/downtown');
  const synced = page.locator('.dt-synced').first();
  await expect(synced).toBeVisible();
  const next = page.locator('.dt-hero + .dt-section');
  await expect(next).toHaveCount(1);
  const a = (await synced.boundingBox())!;
  const b = (await next.boundingBox())!;
  expect(b.y - (a.y + a.height)).toBeLessThanOrEqual(48);
});
