/**
 * Generates server/elric/help-index.ts (Elric's help tool) from the rendered public docs, so
 * Elric only ever sees what https://centralcity.ai/docs publishes. Run: pnpm tsx
 * scripts/elric-help-index.ts. tests/elric-help.test.ts fails when the committed file is stale.
 */
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { format, resolveConfig } from 'prettier';
import { ORIGIN, PUBLIC_DOCS, renderPublicDocs } from './public-docs/build.js';
import type { HelpSection } from '../server/elric/help.js';

export function buildHelpIndex(root: string): HelpSection[] {
  const pages = renderPublicDocs(root);
  const out: HelpSection[] = [];
  for (const doc of PUBLIC_DOCS) {
    const text = pages.get(`docs/${doc.slug}.md`);
    if (!text) continue;
    const url = `${ORIGIN}/docs/${doc.slug}.md`;
    let heading = 'Overview';
    let lines: string[] = [];
    let fenced = false;
    const flush = () => {
      const body = lines
        .join('\n')
        .replace(/\n{3,}/g, '\n\n')
        .trim();
      if (body) out.push({ slug: doc.slug, title: doc.title, url, heading, text: body });
      lines = [];
    };
    for (const line of text.split('\n')) {
      if (/^(```|~~~)/.test(line)) fenced = !fenced;
      const match = !fenced && /^#{2,3} (.+?)\s*$/.exec(line);
      if (match) {
        flush();
        heading = match[1]!;
      } else if (!/^# /.test(line)) lines.push(line);
    }
    flush();
  }
  return out;
}

export async function helpIndexModule(root: string): Promise<string> {
  const file = join(root, 'server/elric/help-index.ts');
  const text = [
    '// Generated by scripts/elric-help-index.ts from the rendered public docs. Do not edit.',
    // Split so the release builder's import check does not read this text as an import.
    `import type { HelpSection } from ${"'./help.js'"};`,
    '',
    `export const HELP_INDEX: readonly HelpSection[] = ${JSON.stringify(buildHelpIndex(root), null, 1)};`,
    '',
  ].join('\n');
  return format(text, { ...(await resolveConfig(file)), filepath: file });
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const root = join(fileURLToPath(new URL('.', import.meta.url)), '..');
  writeFileSync(join(root, 'server/elric/help-index.ts'), await helpIndexModule(root));
}
